name: form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form
  State and Business Logic from the User Interface. Async Validation, Progress,
  Dynamic fields, and more.
version: 0.19.1
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^6.0.0
  bloc_test: ^7.0.0
  collection: ^1.14.11
  equatable: ^1.2.0
  meta: ^1.1.6
  mockito: ^4.1.1
  pedantic: ^1.8.0+1
  quiver: ^2.0.5
  rxdart: ^0.25.0
  uuid: ^2.0.4

dev_dependencies:
  test: ^1.6.0
